### ISSUE TITLE
首先问题来了

### ISSUE THREAD

**Issue by HydrogenDeuterium** [uupers/SciAni#1]
这个东西的主题是什么？
物理？
数学？
还是什么别的？

**Comment by Hansimov** [comment]
我初步的想法是，讲解一些**有用**但是一直没有搞懂的**基本概念**和**常见问题**，领域可能是**数学和工程的交叉处**。

这类视频比较考验数学和工程的功底，每次做视频之前也需要花大量的时间查阅资料和理解。好处是产出的作品质量比较高。

可以参见我刚提出的话题：[第一期视频的主题？](https://github.com/uupers/SciAni/issues/2)
