### ISSUE TITLE
第一期视频的主题？

### ISSUE THREAD

**Issue by Hansimov** [uupers/SciAni#2]
下面是我一直想深入研究且做成视频的主题。

大家可以投票选一个最想看的，或者提出新的主题。

我的想法是，做了第一个，熟悉了流程，之后的就好办了。

* 快速傅里叶变换的动态演示？
* 真/伪随机数是怎样产生的？
* 为什么（狭义上的）正多面体只有五种？
* RSA/AES 的工作原理
* 如何通俗易懂地解释『卷积』？
* 如何通俗易懂地解释『高斯分布』？
* 什么是图灵机？
* 什么是 L System？
* 如何通俗易懂地解释『线性移位反馈寄存器（LFSR）』？
* 如何从零开始造出一个二维码？

**Comment by HydrogenDeuterium** [comment]
嗯……这里所有带引号的我都看不懂……
我倾向于这个：真/伪随机数是怎样产生的？

**Comment by yxlllc** [comment]
图灵机不错

**Comment by HydrogenDeuterium** [comment]
@yxlllc 个人感觉图灵机比较抽象，第一个视频我觉得偏向试水性质，可能应该选具体一点的……

**Comment by Hansimov** [comment]
截至北京时间 `2018-2-19 21:31:09`，10 选项 9 人 26 票，几个“高票”的主题为：
* 【5 票】真/伪随机数是怎样产生的？
* 【4 票】如何从零开始造出一个二维码？
* 【4 票】为什么（狭义上的）正多面体只有五种？
* 【3 票】如何从零开始造出一个二维码？
* 【3 票】RSA/AES 加密算法的工作原理

**最高票选项发生变动**：https://github.com/uupers/SciAni/issues/2#issuecomment-366867645

~~因此近日将开始视频『**真/伪随机数是怎样产生的**』的筹备工作。~~

~~主题名称可能有所变动，比如：~~
* ~~为什么算法生成的都是『伪』随机数~~
* ~~如何从零开始制作一个『伪随机数发生器』~~
* ~~形象展示经典『伪随机数发生器』的工作原理~~
* ~~······~~

**Comment by Hansimov** [comment]
截至北京时间 `2018-2-20 13:01:32`，投票结束，10 选项 13 人 35 票，几个“高票”的主题为：
* 【6 票】如何从零开始造出一个二维码？
* 【5 票】为什么（狭义上的）正多面体只有五种？
* 【5 票】真/伪随机数是怎样产生的？
* 【4 票】如何通俗易懂地解释『卷积』？
* 【4 票】如何通俗易懂地解释『高斯分布』？

因此近日将开始视频『**如何从零开始设计一个二维码？**』的筹备工作。
