### ISSUE TITLE
【二维码#01】QR 码的基础知识

### ISSUE THREAD

**Issue by Hansimov** [uupers/SciAni#4]
# 前言
第一期科普动画视频的主题是二维码。
主要想介绍一下二维码中一些有意思的设计。事实上，每一个设计都是为了解决人们曾经碰到的各种问题，每一个看似平凡的做法，背后其实蕴含了许多人的智慧和心血。

兵马未动，粮草先行。在做视频之前，有必要积累足够的知识，熟悉必要的工具。所以我就先写了这系列的文章，等到时机成熟，你们就能看到动画视频啦！（所以先忘了我们要做视频这回事吧~ :sunglasses:）

目前大多数已有的文章都比较侧重讲解二维码的基础知识和基本原理，并没有花太多的精力来阐述**这样设计是为了解决什么问题**。
因此，本系列的最终目标，就是展示在二维码设计过程中涌现出的各种问题，以及为了解决这些问题提出的各种方法。这些方法并不是凭空产生的，而是有着坚实的数学理论和工程技术作支撑。

书上那些天花乱坠的数学公式令人望而生畏，然而一旦它们用在与生活息息相关的地方，很多事情就变得有趣起来了。

当然咯，在深入探究二维码背后的故事之前，我们还是得老老实实地看一下，当前的二维码到底是个啥玩意。

前面可能会出现各种各样的图案、公式和符号，不过我保证，它们一定不会引起你任何的不适。

好的，各位乘客，我们的旅途即将开始，你们可要坐稳咯！

**Comment by Hansimov** [comment]
# 资料来源
二维码其实有很多种，我们今天见到的大部分都是 QR 码，即 Quick Response Code（快速响应码）。
不过官方指出，尽管该码的目标是快速响应，但官方名称就是“QR 码”，不能将其视作“快速响应”码的简写。

目前中文网络上的绝大多数文章，内容基本都来自以下几个链接：
* 官网（英文）：http://www.qrcode.com/en/
* 官网（中文）：http://www.qrcode.com/zh/
* Wikipedia：https://en.wikipedia.org/wiki/QR_code
* QR 码标准：https://www.iso.org/search.html?q=18004

# 版本变化
需要对上面的最后一个链接做些说明。ISO/IEC 18004 对 QR 码进行了标准化，链接给出的就是 “18004” 在 ISO 官网上的搜索结果。标准的修订和变迁可以参考下面这张图：
<img src = "https://github.com/uupers/SciAni/raw/master/QR%20Code/images/iso-18004-revisions.png">

可以看到标准的版本变化情况为：2000 ⟹ 2006 ⟹ 2006（2009 年修订）⟹ 2015。
2000、2006、2015 分别对应的是第 1、2、3 版。
目前采用的是 2015 年 2 月发布的第 3 版以及 2009 年的修订，2000 和 2006 的版本均弃用。

由于 2015 的标准是要付费购买的，官方只提供几页的预览，因此目前在网络上能找到完整文档的都是 2000 和 2006 的，绝大多数文章也都是参考这两版的标准文档。
我这系列文章将主要参考 2006 的文档，不过 2000 的文档也会派上用场——有时候我们能从早期的版本挖掘出更多有意思的细节。

**Comment by Hansimov** [comment]
# 文档目录及简介
2000 和 2006 的版本均为 114 页，2015 版本的文档有 117 页。因此从头到尾讲解一遍 QR 码是不现实的。
比较合理的做法是在此列出章节目录，给出简要介绍，这样以后需要查阅相关内容时，只要跳到对应章节就可以了。

2006 版本的目录及其及简介如下列各小节所述。

# 文档目录一览 （1~3）
## Foreword（前言）
这部分就是简单介绍一下 ISO 和 IEC 是干啥的。

## Introduction （导言）
这部分表述了 QR 码家族的几个成员之间的区别，包括：
* QR Code Model 1
* QR Code Model 2
* QR Code 2005
* Micro QR Code

大家也可以点进官网的这个链接查看：[QR 码的种类](http://www.qrcode.com/zh/codes/)。
嗯，我知道你们懒得点进去看，我直接截张图好了：

![](https://github.com/uupers/SciAni/raw/master/QR%20Code/images/qr-code-types.png)

## 1 Scope （范围）
大概就是说我们这个文档啊，涵盖了 QR Code 2005 的方方面面，什么数据字符的编码方式，符号格式，纠错规则，以及和 QR Code Model 1 的不同，等等等等。

## 2 Conformance（一致性）
这部分说了几个方面：
1. 遵照这个文档（2006版本）所述标准生产的设备，对于 QR Code Model 1 可能不能识别，但是能识别 QR Code Model 2。
2. 遵照 2000 版本标准生产的扫描和打印的设备，可能不能识别遵照 2006 版本标准生成的全部符号。
3. 遵照 2006 版本标准的符号，也不能由遵照 2000 版本标准生产的设备扫描和打印。
4. 建议新的和开放的系统应用使用 QR Code 2005。

总之是说，新的东西未必能兼容旧的，建议你们开始用新的。

## 3 Normative references （标准引用）
列了这个文档用到的一堆其他标准。
反正我也懒得看。

**Comment by Hansimov** [comment]
# 文档目录一览（4~5）

## 4 Terms and definitions, mathematical and logical symbols, abbreviations and conventions（术语和定义、数学和逻辑符号、缩写以及约定）
哇，这个标题真的好长。
### 4.1 Terms and definitions（术语和定义）
这部分列了 25 个术语和定义，这里空白太小，写不下简介。而且光写字你们也不知道长得啥样啊。
虽然我没写，但是很重要哦！
不过放心啦，以后我应该会专门做一张图来展示这些概念的。

### 4.2 Mathematical and logical symbols（数学和逻辑符号）
| 符号 | 含义 |
| --- | --- |
| div | 整数除法运算 |
| mod | 除法运算所得的余数 |
| XOR | 异或运算，用 &oplus; 表示 |

嗯，简单到我都不想列出来。

### 4.3 Abbreviations（缩写）

| 缩写 | 含义 |
| --- | --- |
| BCH | Bose-Chaudhuri-Hocquenghem |
| ECI | Extended Channel Interpretation |
| RS | Reed-Solomon |

第一个和第三个你们大概都知道，就是通常所说的 BCH 码和 RS 码啦（哪里通常了啊喂），以人名命名的东西一般都是很酷炫的。
ECI 还真找不到现成的中文翻译。不过不懂没关系，暂时没用到的东西我们就不要纠结啦，就当无事发生过。

### 4.4 Conventions（约定）
#### 4.4.1 Module positions（模块位置）
#### 4.4.2 Byte notation（字节记号）
#### 4.4.3 Version references（版本参考）

## 5 Symbol description（符号描述）
### 5.1 Basic characteristics（基本特点）
### 5.2 Summary of additional features（附加特性概要）
### 5.3 Symbol structure（符号结构）
#### 5.3.1 Symbol Versions and sizes（符号版本和尺寸）
#### 5.3.2 Finder pattern（）
#### 5.3.3 Separator（）
#### 5.3.4 Timing pattern（）
#### 5.3.5 Alignment patterns（）
#### 5.3.6 Encoding region（）
#### 5.3.7 Quiet zone（）

**Comment by Hansimov** [comment]
## 文档目录一览（6）
6 Requirements
6.1 Encode procedure overview
6.2 Data analysis
6.3 Modes
6.3.1 Extended Channel Interpretation (ECI) mode
6.3.2 Numeric mode
6.3.3 Alphanumeric mode
6.3.4 Byte mode
6.3.5 Kanji mode
6.3.6 Mixing modes
6.3.7 Structured Append mode
6.3.8 FNC1 mode
6.4 Data encoding
6.4.1 Sequence of data
6.4.2 Extended Channel Interpretation (ECI) mode
6.4.3 Numeric mode
6.4.4 Alphanumeric mode
6.4.5 Byte mode
6.4.6 Kanji mode
6.4.7 Mixing modes
6.4.8 FNC1 modes
6.4.9 Terminator
6.4.10 Bit stream to codeword conversion
6.5 Error correction
6.5.1 Error correction capacity
6.5.2 Generating the error correction codewords
6.6 Constructing the final message codeword sequence
6.7 Codeword placement in matrix
6.7.1 Symbol character representation
6.7.2 Function pattern placement
6.7.3 Symbol character placement
6.8 Data masking
6.8.1 Data mask patterns
6.8.2 Evaluation of data masking results
6.9 Format information
6.9.1 QR Code symbols
6.9.2 Micro QR Code symbols
6.10 Version information

**Comment by Hansimov** [comment]
## 文档目录一览（7~9）

7 Structured Append
7.1 Basic principles
7.2 Symbol Sequence Indicator
7.3 Parity Data
8 Symbol printing and marking
8.1 Dimensions
8.2 Human-readable interpretation
8.3 Marking guidelines
9 Symbol quality
9.1 Methodology
9.2 Symbol quality parameters
9.2.1 Fixed pattern damage
9.2.2 Scan grade and overall symbol grade
9.2.3 Grid non-uniformity
9.3 Process control measurements

**Comment by Hansimov** [comment]
## 文档目录一览（10~13）
10 Decoding procedure overview
11 Reference decode algorithm for QR Code 2005
12 Autodiscrimination capability
12 Autodiscrimination capability
13 Transmitted data
13.1 General principles
13.2 Symbology Identifier
13.3 Extended Channel Interpretations
13.4 FNC1

**Comment by Hansimov** [comment]
## 文档目录一览（A~D）
Annex A (normative) Error detection and correction generator polynomials
Annex B (normative) Error correction decoding steps
Annex C (normative) Format information
C.1 Error correction bit calculation
C.2 Error correction decoding steps
Annex D (normative) Version information
D.1 Error correction bit calculation
D.2 Error correction decoding steps

**Comment by Hansimov** [comment]
## 文档目录一览（E~G）
Annex E (normative) Position of alignment patterns
Annex F (normative) Symbology Identifier
Annex G (normative) QR Code 2005 print quality – symbology-specific aspects
G.1 Fixed Pattern damage
G.1.1 Features to be assessed
G.1.2 Fixed Pattern Damage grading
G.2 Grading of additional parameters
G.2.1 Grading of format information
G.2.2 Grading of version information (QR Code symbols)
G.3 Scan grade

**Comment by Hansimov** [comment]
## 文档目录一览（H~J）
Annex H (informative) JIS8 and Shift JIS character sets
Annex I (informative) Symbol encoding examples
I.1 General
I.2 Encoding a QR Code symbol
I.3 Encoding a Micro QR Code symbol
Annex J (informative) Optimisation of bit stream length
J.1 General
J.2 Optimisation for QR Code symbols
J.3 Optimisation for Micro QR Code symbols
J.3.1 Optimisation principles
J.3.2 Capacity of Micro QR Code symbols

**Comment by Hansimov** [comment]
## 文档目录一览（K~N）
Annex K (informative) User guidelines for printing and scanning of QR Code 2005 symbols
K.1 General
K.2 User selection of error correction level
Annex L (informative) Autodiscrimination
Annex M (informative) Process control techniques
M.1 Symbol Contrast
M.2 Assessing Axial Nonuniformity
M.3 Visual inspection for symbol distortion and defects
M.4 Assessing print growth
Annex N (informative) Characteristics of Model 1 symbols
N.1 Model 1 QR Code symbols
N.1.1 Model 1 overall characteristics
N.1.2 Symbol versions and sizes
N.2 Detailed specifications

**Comment by Hansimov** [comment]
## 文档目录一览（文献）
Bibliography

**Comment by KaiserKatze** [comment]
能不能根据2000和2006两次历史更新，以及2015预览版文档，揣测2015版完整的更新有些什么啊？

**Comment by Hansimov** [comment]
> 能不能根据2000和2006两次历史更新，以及2015预览版文档，揣测2015版完整的更新有些什么啊？

较大的变动从预览版的文档目录是可以看出来的。
不过时间有限，意义也不大，所以暂时没有这方面的打算。
你有兴趣可以试一试。
