### ISSUE TITLE
SciAniLab 的风格、标识与片头

### ISSUE THREAD

**Issue by Hansimov** [uupers/SciAni#8]
片头的风格是什么？
片头的时长要多少？
片头的动画什么样？
用什么技术制作？

当然，首先要看看其他视频的片头是什么样的。

**Comment by Hansimov** [comment]
### 片头风格
科技感
黑/蓝/红色系

### 片头时长

**Comment by Hansimov** [comment]
首先看看一些著名电影厂商的片头：[各电影公司片头Logo](https://www.bilibili.com/video/av2210505?from=search&seid=1496831144091403339)
* 风格：气势磅礴的占多（也有很可能是这些本身就是大厂，取样有偏差）
* 时长：大部分都是10秒到30秒

不过由于是电影片头，主题、内容以及风格都和我们的大相径庭，所以仅供参考。
我们还是先看看和科普相关的视频片头是什么样的吧。

---

<p align="center">
<img width=400 src="https://user-images.githubusercontent.com/15179365/38234861-b8fee7de-3751-11e8-8f32-03dac76f4fd0.png"></p>
<p align="center">Minute Physics</p>

* 描述：手+笔+ “Minute Physics”
* 风格：手写，白底（自然光）+黑字+现实中的手
* 时长：1秒

---
<p align="center">
<img width=400 src="https://user-images.githubusercontent.com/15179365/38234924-ecf3d784-3751-11e8-9f69-0b401e843957.png"></p>
<p align="center">3Blue1Brown</p>

* 描述：异色瞳+“3Blue1Brown”
* 风格：黑底白字，蓝棕配色
* 时长：3秒

---
<p align="center">
<img width=400 src="https://user-images.githubusercontent.com/15179365/38234971-239dcc36-3752-11e8-8bbe-38729d1936a7.png"></p>
<p align="center">Mathologer</p>

* 描述：头像+“Mathologer”+公式背景，左侧圆形机构
* 风格：黑色+灰白背景，绿色配字
* 时长：3.5秒

---
<p align="center">
<img width=400 src="https://user-images.githubusercontent.com/15179365/38235704-a018d326-3754-11e8-9e1d-fd4b9d7ff876.png"></p>
<p align="center">PBS Infinite Series</p>

* 描述：“PBS DIGITAL STUDIOS”，三行
* 风格：灰白背景，白灰字，蓝橙绿配色
* 时长：2秒

---
<p align="center">
<img width=400 src="https://user-images.githubusercontent.com/15179365/38235794-f1fc614e-3754-11e8-88aa-6af94896e4b4.png"></p>
<p align="center">柴知道</p>

* 描述：柴犬+“柴知道”+“在知识的海洋里狗刨”
* 风格：白色背景，萌系字体，卡通形象（注意拟人化的领结和眼镜）
* 时长：4.5秒

---
<p align="center">
<img width=400 src="https://user-images.githubusercontent.com/15179365/38236013-80091176-3755-11e8-82a4-d76bb3a46642.png"></p>
<p align="center">混乱博物馆</p>

* 描述：本期主题+“混乱博物馆”+日期+期数+边框修饰
* 风格：白底黑字，四周的装饰如同论文的旁注和脚注，学术感扑面而来
* 时长：2秒

---
其实我还很中意敖厂长的视频开头风格（好几种），不过由于不是科普向，所以这里就没有列举出来。之后记得考虑一下。

**Comment by Hansimov** [comment]
虽然上面只列了6个科普类视频的片头，而且风格各异，但是还是明显可以找到一些共通的要素的：

* **制作者名称**：上述制作者不一而同地在开头就展示了制作者的名称和logo。不过提醒一点，有些其他的科普视频作者没有制作专门的片头，比如 Numberphile，但是在视频开头一定出现这个词。
* **时长较短**：和电影不同，这类科普视频，短则2-3分钟，长也不过20分钟（很少，除了3B1B的某几期）。因此片头就不能太长，普遍集中在2-5秒。（当然，敖厂长的十分钟视频，片头也会达到30秒以上，但是由于效果震撼，所以并不会让观众觉得冗长。）
* **和全片的风格一致**：分钟物理全程手绘，3B1B 黑底+数学动画，Mathologer 真人讲解+典故+公式，PBS 真人讲解+灰绿色背景+精良的动画，柴知道萌萌的画风和小姐姐的配音，混乱博物馆的性冷淡解说加上旁征博引，敖厂长极富年代感和猎奇感的主题与配乐。基本上片头的风格和全片是非常吻合的。

**Comment by Hansimov** [comment]
看完了别人，来想想自己。

### 时长
片头时长大概可以确定了，控制在5秒以内为宜。当然，也完全不必拘泥于已有的规矩，视具体情况调整也是允许的。一切都需要在实践中改进和完善。

### 风格
重点来谈谈片头的风格。而谈风格就不能脱离内容。

LePtC 的物理硬科普系列 [如何狸解](https://github.com/uupers/How2Lexplain)，似乎走的是萌系画风。这和LePtC 的一贯形象是相符的。

组织的 logo 最终确定为我当时五秒钟的即兴之作：
<p align="center">
<img width =200 src="https://user-images.githubusercontent.com/15179365/38238144-8f83d658-375b-11e8-83c5-fba63961a361.png"></p>

即 UUP （Unkown Unscientific Producers）的象形，也是一个吐舌头的笑脸。

尽管 SciAniLab（赛爱你）项目是独立于爬虫组和狸解组的，但是也应该有一些东西是贯穿各个项目的。然而当前各个项目组的成果甚少，也就谈不上形成了什么风格。除了科技这一宏大的主题之外，似乎很难找到第二个共同点。

所以有必要积极探索各自的风格，SciAni 也就可以自由发挥了。

我对风格的考虑，和我当初绘制组织 logo 时的想法是一致的：
**科普应当是友好的、幽默的、有趣的。**

**首先是要友好**。
别人认识你，才可能听你说话；别人喜欢你，才愿意听你说话；别人爱上你，才会主动跟你说话。
科普嘛，现在不缺乏『科』了，『普』还有很长的路要走。额，这个话题太大了，我怕又忍不住扯太多。收！
总之选题要尽可能贴合大家生活中常见的东西，科技无处不在，与我们息息相关，但是只有你告诉人们科技带来的便利，人们才会对这些感到惊奇，才会对科技产生好感，然后再经过更长的时间，才会尊重和信赖科技工作者，才能在大众当中培养起广泛的科学素养。
我们的目标应当是普罗大众，至少也是视频网站上的年轻一代。我们要想让他们加入我们的队伍，就一定要让他们感受到我们这里的温暖。

**其次是要幽默**。
工作太多，快乐太少。人们上网看视频是为了娱乐，学知识也只是学有用的那部分，或者有利于社交的那部分。
如果我们的观众听不懂我们在说什么（这是我们努力避免，但一定会出现的情况），那至少也应当让他们在这几分钟内，暂时忘却生活的烦恼。
幽默不同于逗乐，科普中的幽默应当是深层次的幽默。幽默的表达也应当建立在友好的关系之上。如何把握幽默的度，是一个需要仔细考量的事情。
幽默这一点十分依赖制作者的个人风格。你自己的性格中首先得有幽默的成分，你的作品才有可能幽默起来。

**最后是要有趣**。
有趣似乎和幽默重叠了，然而并不是。
因为在科学家眼里，某个结论可能是有趣的，但大众却毫无感觉。因为双方对“有趣”的定义和理解完全不同。
幽默侧重于视频内容的表达方式，有趣侧重于视频主题的涉及领域。有趣的主题以生硬的口吻讲出来，同样枯燥乏味。幽默的口吻阐述艰涩的理论，也会让很多人不知所云。
因此在幽默的前提下，还得有有趣的主题。这样才能最大程度地吸引观众的注意力，让他们获得快乐，感到愉悦，如果更好的话，还能喜欢上我们。

---
额，写了这么多对内容风格的理解，严重跑题。然而我懒得再开一个贴子了。

总之，贯穿始终的想法是：**要让观众从视频中得到快乐，顺便学点知识，如果可以，还能喜欢我们**。

**Comment by LePtC** [comment]
写的很赞！Mathematica 玩家交流协会的片头你觉得怎么样？如果需要我可以用 Flash 帮你制作

<p align = "center">
<img width= 400 src="https://user-images.githubusercontent.com/6371171/38242981-bc0ee784-3725-11e8-9c5e-638ca230a55f.jpg"></p>
<p align = "center">Mathematica 玩家交流协会</p>

**Comment by Hansimov** [comment]
写到这里，我们是不是就可以得到一个推论，那就是我们的片头要做得活泼一点呢？

这也是我一开始得到的。然而仔细一想，发现不是那么一回事。

因为上面一小节所说的“风格”，并不是指我们的**视听的效果**，而是**选题和内容的基调**。
而我之前说，那几个片头“和全片的风格一致”，也主要是指给人的视听感受前后一致，而不是说内容和画风一致。比如 3B1B 虽然画风冷峻，但是文案却很活泼（调皮的π以及各种令人会心一笑的细节）。

因此，我们可以这样说：
**选题和文案是幽默有趣的，充满人文关怀；而试听效果上是可以高冷的，比如低调奢华的配色，以及充满科技感的动画**。
这两者并不矛盾。外表和内核，完全可以拥有不同的形态。

**Comment by Hansimov** [comment]
@LePtC 
> Mathematica 玩家交流协会的片头你觉得怎么样

你是说这个视频的片头吧：[Mathematica 也能打爆别踩白块？奥义：线性回归](https://www.bilibili.com/video/av19070980/)
我觉得你这个片头很好，我目前的想法也是做成这个类型的。
Logo+项目/制作人的名称+合适的配色。

---
> 如果需要我可以用 Flash 帮你制作

嗯，我打算先自己做一版出来，如果到时候你觉得有地方可以改进，欢迎斧正~:smirk:

**Comment by Hansimov** [comment]
SciAni 更名为 SciAniLab 了，原因有二：
* 谷歌搜索 SciAni 会出来一大堆结果，而 SciAniLab 目前还没有任何结果。
改名后辨识度明显更高。
* SciAniLab 的缩写是 SAL，而 SAL 9000 是《2010：太空漫游》里的女性 AI。
我本来是打算将 HAL 9000 的形象作为 SciAniLab 的 logo 的，改名后，也就顺水推舟，决定把形象改成 SAL 9000 的样子。

<p align = "center">
<img width=200 src="https://user-images.githubusercontent.com/15179365/38251135-321faba4-3783-11e8-9f12-72da7c9e17de.jpg"></p>
<p align = "center">HAL 9000</p>

<p align = "center">
<img width=200 src="https://user-images.githubusercontent.com/15179365/38251136-32505f56-3783-11e8-8cb7-a079f3e4d9ca.png"></p>
<p align = "center">SAL 9000</p>

知道 HAL 的人很多，因为《2001：太空漫游》家喻户晓。但是知道 SAL 的人可能就寥寥无几了。
关于 SAL 9000 的基本资料，可以读一读这篇文章：[2010 Odyssey Two Archive: SAL-9000](http://2010odysseyarchive.blogspot.com/2015/01/sal-9000.html)

这种科幻作品中的形象，很贴合我们的主题，又足够小众（相比 HAL），因此选择它作为我们的 logo 真的是再好不过了。
加上克拉克本身就既是科幻作家，也是科普作家，而且参与过军方技术工作，经受过数学和物理的科班教育，科学和技术可以说是他投入一生的事业。
他也将是我做这个项目的精神领袖，鼓舞着我一直向未知的领域进发。
总之，这个 logo 是无比契合这个项目的宗旨的，我实在想不到有什么比它更合适的了。

不过我并不打算直接将影视中的图片截取下来，不管是否存在版权问题，直接拷贝现有的东西，都明显不符合我们的原创精神。

所以我打算通过编程绘制 SciAniLab 的 logo。

绘制 logo 将是制作片头的第一步，后面的事情，后面再说。
绘制过程会新开一个贴子，见：[【绘图#002】SciAniLab 的 logo](https://github.com/uupers/SciAniLab/issues/9)
